Only accept lower case standard types
GENIVI/vss-tools pull request #26
Opened 2020-11-10 09:59 UTC by SebastianSchildt

datatype parsing is more strict.

The error message is not very good, becasue it doesn't tell you in which file the error has been encountered. But I didn't make it worse....

At least this will enforce some consistency, once it is used in travis

2020-11-10 14:05 UTC, gunnarx requested changes

2020-11-12 19:04 UTC, SebastianSchildt commented on model/constants.py
> +        raise Exception("Invalid VSS datatype %s, valid types are %s" % (name, VSSDataType.values()))
I wanted to argue, that this is not really helping as our tools are sort of alpha quality and have the usability of Emacs. On a good day. But I figured, it is easier I just add the hint to the error message. 

Well... Now I did sort of both 😁  Progress!

2020-11-17 18:33 UTC, gunnarx approved these changes

2020-11-17 20:43 UTC, gunnarx commented
Squashed and merged manually.

2020-11-17 20:43 UTC, closed without merging