Feature/parser check core attributes
GENIVI/vss-tools pull request #39
Opened 2021-02-11 16:47 UTC by SebastianSchildt

This fixes #38 

merge order #34  #35  and then this

This does not change the default behaviour (i.e. CSV parser not changed, output the same), but will print warnings if non-core attribtes are found.

With current vspec

```
$ python3 vspec2json.py  -i :test.id -I ../vehicle_signal_specification/spec/ ../spec/VehicleSignalSpecification.vspec    vsstest.json
Loading vspec...
Warning: Non-core attribute "value" in elment CurrentOverallWeight found.
Warning: Non-core attribute "value" in elment CurbWeight found.
Warning: Non-core attribute "value" in elment GrossWeight found.
Warning: Non-core attribute "value" in elment MaxTowWeight found.
Warning: Non-core attribute "value" in elment MaxTowBallWeight found.
Warning: Non-core attribute "value" in elment Length found.
Warning: Non-core attribute "value" in elment Height found.
Warning: Non-core attribute "value" in elment Width found.
Warning: Non-core attribute "value" in elment ChargePortFlap found.
Warning: Non-core attribute "value" in elment ChargePlugType found.
Warning: Non-core attribute "value" in elment Mode found.
Warning: Non-core attribute "value" in elment StartStopCharging found.
Warning: Non-core attribute "value" in elment Mode found.
Recursing tree and creating JSON...
All done.
```
(for layers non-core attributes might be desired)

Once all spec bugs are fixed, we can switch Travis to run strict mode with `-s` parameter

```
python3 vspec2json.py -s  -i :test.id -I ../vehicle_signal_specification/spec/ ../spec/VehicleSignalSpecification.vspec    vsstest.json
Loading vspec...
Warning: Non-core attribute "value" in elment CurrentOverallWeight found.
You asked for strict checking. Terminating.
```
@danielwilms  pls check

2021-02-16 18:37 UTC, gunnarx requested changes

2021-02-16 18:37 UTC, gunnarx commented on model/vsstree.py
> +class NonCoreAtrributeException(Exception):
Typo A**TRR**ibute -> A**TTR**ibute

2021-02-23 14:31 UTC, gunnarx approved these changes

2021-02-23 14:38 UTC, gunnarx commented
Looks OK now (if we squash the related commits when merging).

But one question - should not all tools be changed to accept the -s flag?

(Also, if I may recommend the convention to indicate the file (or sometimes the program or subsystem) first in the commit message):

For example:
`vspec.py: Optionally terminate on non-core attributes`
and
`vspec2json.py:  Add -s strict mode for non-core attributes`

If we assume that both 07db4ed and 4c45064 were kept as separate commits, then this shows more directly that the feature first was added to in vspec, then in vspec2json.  If we get bugs in one of the file, it is easier to scan which other commits might be worth checking, and so on.

2021-02-23 15:22 UTC, SebastianSchildt commented
Thanks for reviewing.

wrt. to udating all tools to support -s: Yes, probably, but there is also lot more to "beautify", i.e. the arguments parsing is horrible (no argparse just that ancient getopt wrapper), and actually the code between 2json and 2csv is so similar, they should maybe be merged/share more code.

But I did not want to discuss/mix so many different aspects in a single PR, and tried to keep changes to a minimum.  

Commit "granularity" is always a matter of taste. If found at VSS we prefer large/squashed commits, on the other hand I once had a colleague, that made different commits even if he only changed one file in one go at two different places (yes git can do that) 😁 

In the commit messages I can try to remember in the future to mark the "component"/location first

2021-02-23 16:08 UTC, danielwilms approved these changes
works!

2021-02-23 18:14 UTC, danielwilms commented
@gunnarx please merge 23/02/21

2021-02-24 14:29 UTC, merged